name: Deploy to BeamUp
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Stremio/beamup-deploy-action@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          BEAMUP_HOST: ${{ secrets.BEAMUP_HOST }}
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
